[package]
name = "dictionary-attack"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
terminal-spinners = "0.3.1"
clap = { version = "3.0", features = ["derive"] }
